services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: thryve_api_db
    ports:
      - 5432:5432
